### PR TITLE
Network hydro

### PR DESCRIPTION
**Pull request by mcwimm**
New below-ground competition concept combining SimpleHydro and SimpleNetwork, i.e. simple plant-soil feedback and networking

### CODE REVIEW

**Review by jbathmann — COMMENTED** [review]
Nice and clean PR!

Just two remarks/questions:
-What about the ppt/ g per kg problem between simplehydro and fixedsalinity? does this lead to problems? Do you think it should be fixe, before we merge this pr?
-Are there some troubles in generating the .dox-files? are they up to date in this pr and in pr #81?

**Comment by mcwimm** [comment]
> Nice and clean PR!

Thanks!

> Just two remarks/questions:
> -What about the ppt/ g per kg problem between simplehydro and fixedsalinity? does this lead to problems? Do you think it should be fixe, before we merge this pr?

It would be nice if we agree on a uniform system. At the moment it works with ppt as 'defined' in SimpleHydro. However, no documentation for SimpleHydro exists, thus no one knows what's required.

> -Are there some troubles in generating the .dox-files? are they up to date in this pr and in pr #81?

There's no documentation for this concept because I don't know the meaning for most parameters required in SimpleHydro...

**Comment by jbathmann** [comment]
Is thisone ready?

**Comment by mcwimm** [comment]
> Is thisone ready?

It works but the documentation is still missing...

**Comment by jbathmann** [comment]
> > Is thisone ready?
> 
> It works but the documentation is still missing...

but now, it is up to date...?

**Comment by mcwimm** [comment]
> > > Is thisone ready?
> > 
> > 
> > It works but the documentation is still missing...
> 
> but now, it is up to date...?

Yes :)

**Pull request merged**
